from . import general_type
from . import ir_attachemnt
from . import crm_stage
from . import product_template
from . import account_move
from . import sale_order
from . import res_partner
from . import crm_lead
from . import target